### PR TITLE
Community Organizer Playbook

### PR DESCRIPTION
**Pull request by xaur**
Rendered draft:

https://github.com/decredcommunity/guidelines/blob/commorg/community-organizer-playbook.md

You can leave feedback by commenting in this thread.

### CODE REVIEW

**Comment by xaur** [comment]
(1) The following docs are mentioned in the text, we need to link them if they are public or say how to access them:

- Events Guide
  - or did it mean Events section of this doc?
- Social Media Guidelines
- Social Media Playbook PDF
  - are the two above the same?
- Crypto Twitter Influencer List

**Comment by xaur** [comment]
(2) "Being a Decred Resource" - is it just me or does it sound a bit too business-y? How about "Representative" or "Ambassador" or "Guide"? (I can dig for more)

(3) "is paid for and supported by the Decred stakeholders" - or Treasury?

(4) "onboarding process": can also link to https://docs.decred.org/contributing/overview/

(5) how about we add a note somewhere to submit event reports to https://github.com/decredcommunity/events ?

**Comment by xaur** [comment]
(6) Structure: "Expectations & Conduct" and "Tips" talk mostly about events but are not nested under Events. If this is by design, what's the idea?

**Comment by xaur** [comment]
(7) Expense Guidelines ideas:

- add notice about volatility risk that can screw one's labor pay and reimbursement
- add short hint what proposal token to use
- clarify whether "$250 for events up to 10 people" includes Community Organizers work hours
- why this section doesn't include the CMS example?

**Comment by xaur** [comment]
(8) Since we have a CMS example and Expense Guidelines at the end, wonder if we should extend the CMS example to include event expenses? Current example table only has labor hours billed, but there's no example how to reimburse for travel, swag, food, drinks, etc.

**Comment by xaur** [comment]
(9) When I replaced the CMS image with Markdown table I removed the reported social media follower counts for two reasons: to reduce table size and because it is not the best approach.

It is not the best approach because it requires more manual work from contractors, while at the same time collecting and visualizing these numbers could and should be [automated](https://proposals.decred.org/proposals/5d9cfb07aefb338ba1b74f97de16ee651beabc851c7f2b5f790bd88aea23b3cb/comments/13).

I guess having those numbers _somewhere_ was important because it was mentioned in Measurement section. Not sure if we should add them back into the example invoice.

**Comment by xaur** [comment]
(10) I would add titles and short relevant info to References at the end.

**Review by Dustorf — APPROVED** [review]

**Review by Dustorf — COMMENTED** [review]
Looks good to me

**Comment by xaur** [comment]
I've edited the commit on master to fix author.

**Pull request merged**
